version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.34
    - 15.0.0
  - dependency-name: netlify-cli
    versions:
    - 3.19.0
    - 3.21.12
    - 3.21.2
    - 3.21.5
    - 3.22.0
  - dependency-name: eslint-plugin-testing-library
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.8
    - 24.2.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
