pull_request_rules:
  - name: "Automatic merge of Greenkeeper PRs on CI success"
    conditions:
      - "author=greenkeeper[bot]"
      - status-success=greenkeeper/verify
      - status-success=ci/circleci: build
    actions:
      merge:
        method: squash
