pull_request_rules:
  - name: "Automatic merge of dependabot PRs on CI success"
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: squash
