pull_request_rules:
  - name: "Automatic merge of Synk PRs on CI success"
    conditions:
      - author=synk-bot
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: squash
