version: 2.1
jobs:
  build:
    working_directory: ~/york-recycling
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v3-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v3-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test
