version: 2.1
jobs:
  build:
    working_directory: ~/york-recycling
    docker:
      - image: circleci/node:13
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v2-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v2-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "junit/junit.xml"
          store_artifacts:
            path: coverage
